# Generated by Django 6.0.2 on 2026-02-19 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('template', models.FileField(upload_to='templates')),
            ],
        ),
        migrations.CreateModel(
            name='DocumetsUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='documents')),
                ('documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='documets',
            name='user',
            field=models.ManyToManyField(through='documents.DocumetsUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
